// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuDp0Z8kkmUZK6mmzvWCjfXkx2mQ2IH_k',
    appId: '1:555137208600:web:87c4e863e68fde78d44e6d',
    messagingSenderId: '555137208600',
    projectId: 'cmsc-23-b2l-qlramos',
    authDomain: 'cmsc-23-b2l-qlramos.firebaseapp.com',
    storageBucket: 'cmsc-23-b2l-qlramos.appspot.com',
    measurementId: 'G-KMXVE93YVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSpHwGmvjhEjHOqM7XnYcNXKEdVIgUxC0',
    appId: '1:555137208600:android:9654e07d1205f96ad44e6d',
    messagingSenderId: '555137208600',
    projectId: 'cmsc-23-b2l-qlramos',
    storageBucket: 'cmsc-23-b2l-qlramos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsePWyaSxA0mna0XGzKr8Y2lQ5YYNon2g',
    appId: '1:555137208600:ios:785a1454d91a9577d44e6d',
    messagingSenderId: '555137208600',
    projectId: 'cmsc-23-b2l-qlramos',
    storageBucket: 'cmsc-23-b2l-qlramos.appspot.com',
    iosClientId: '555137208600-0kp8d5nkp5r0vgqf3sspklvuttrf6u0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsePWyaSxA0mna0XGzKr8Y2lQ5YYNon2g',
    appId: '1:555137208600:ios:785a1454d91a9577d44e6d',
    messagingSenderId: '555137208600',
    projectId: 'cmsc-23-b2l-qlramos',
    storageBucket: 'cmsc-23-b2l-qlramos.appspot.com',
    iosClientId: '555137208600-0kp8d5nkp5r0vgqf3sspklvuttrf6u0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
